from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session
from app.db.database import get_db
from app.schemas.recommendation import RecommendationRequest, RecommendationResponse
from app.core.recommendation import get_recommendations

router = APIRouter()

@router.post("/", response_model=RecommendationResponse)
def get_recovery_recommendations(request: RecommendationRequest, db: Session = Depends(get_db)):
    """
    Takes a disrupted node and returns ranked alternative nodes (based on cost, lead time, and reliability),
    along with a plain-text recommendation generated by an LLM (Groq).
    """
    ranked_alts, llm_rec = get_recommendations(db, request)
    return RecommendationResponse(
        ranked_alternatives=ranked_alts,
        llm_recommendation=llm_rec
    )
